runtime: python39

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "aliro_vision_api_key.json"
  FIREBASE_PROJECT_ID: "aliro-436816"
  FIREBASE_CREDENTIALS_PATH: "aliro-e0742-firebase-adminsdk-jm9vr-a3f9187e19.json"

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto